# Atividade de series temporais

Essa atividade é para um fim didático de estudar series temporais por completo, classifica-las e aprofundar o conhecimento

## Carregando a base

#### Base que guarda o preço de casas vendidas no periodo de 2007-2019

In [180]:
import kagglehub

path_sales = kagglehub.dataset_download("htagholdings/property-sales")

print("Path to dataset files:", path_sales)

Path to dataset files: C:\Users\miguelaraujo-ieg\.cache\kagglehub\datasets\htagholdings\property-sales\versions\3

#### Base que guarda o consumo de energia de casas no periodo de 2006 a 2010

In [181]:
path_eletricpower = kagglehub.dataset_download("uciml/electric-power-consumption-data-set")

print("Path to dataset files:", path_eletricpower)

Path to dataset files: C:\Users\miguelaraujo-ieg\.cache\kagglehub\datasets\uciml\electric-power-consumption-data-set\versions\1

In [182]:
import pandas as pd
import os
df_property_sales = pd.read_csv(os.path.join(path_sales, "raw_sales.csv"))
df_electric_power = pd.read_csv(os.path.join(path_eletricpower, "household_power_consumption.txt"), sep=";")

C:\Users\miguelaraujo-ieg\AppData\Local\Temp\ipykernel_24884\2262707762.py:4: DtypeWarning: Columns (0: Global_active_power, 1: Global_reactive_power, 2: Voltage, 3: Global_intensity, 4: Sub_metering_1, 5: Sub_metering_2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_electric_power = pd.read_csv(os.path.join(path_eletricpower, "household_power_consumption.txt"), sep=";")

In [183]:
df_electric_power

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0
...,...,...,...,...,...,...,...,...,...
2075254,26/11/2010,20:58:00,0.946,0.0,240.43,4.0,0.0,0.0,0.0
2075255,26/11/2010,20:59:00,0.944,0.0,240.0,4.0,0.0,0.0,0.0
2075256,26/11/2010,21:00:00,0.938,0.0,239.82,3.8,0.0,0.0,0.0
2075257,26/11/2010,21:01:00,0.934,0.0,239.7,3.8,0.0,0.0,0.0
2075258,26/11/2010,21:02:00,0.932,0.0,239.55,3.8,0.0,0.0,0.0

#### Transformando em series temporais

In [184]:
serie_property_sales = df_property_sales[["price","datesold"]]

In [185]:

serie_property_sales['datesold'] = pd.to_datetime(
    serie_property_sales['datesold'],
    errors='coerce'
)

serie_property_sales = serie_property_sales.dropna(subset=['datesold'])

serie_property_sales = serie_property_sales.set_index('datesold')

serie_property_sales = serie_property_sales.sort_index()

serie_property_sales = serie_property_sales.resample('MS').median()

In [186]:
serie_property_sales

               price
datesold
2007-02-01  407500.0
2007-03-01  328000.0
2007-04-01  465000.0
2007-05-01  339500.0
2007-06-01  451000.0
...              ...
2019-03-01  602500.0
2019-04-01  623472.0
2019-05-01  632500.0
2019-06-01  671000.0
2019-07-01  565350.0

[150 rows x 1 columns]

In [187]:
df_electric_power

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0
...,...,...,...,...,...,...,...,...,...
2075254,26/11/2010,20:58:00,0.946,0.0,240.43,4.0,0.0,0.0,0.0
2075255,26/11/2010,20:59:00,0.944,0.0,240.0,4.0,0.0,0.0,0.0
2075256,26/11/2010,21:00:00,0.938,0.0,239.82,3.8,0.0,0.0,0.0
2075257,26/11/2010,21:01:00,0.934,0.0,239.7,3.8,0.0,0.0,0.0
2075258,26/11/2010,21:02:00,0.932,0.0,239.55,3.8,0.0,0.0,0.0

In [188]:
df_electric_power['datetime'] = pd.to_datetime(
    df_electric_power['Date'] + ' ' + df_electric_power['Time'],
    format='%d/%m/%Y %H:%M:%S'
)

df_electric_power = df_electric_power.set_index('datetime')
df_electric_power

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
datetime,,,,,,,,,
2006-12-16 17:24:00,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
2006-12-16 17:25:00,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2006-12-16 17:26:00,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
2006-12-16 17:27:00,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
2006-12-16 17:28:00,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0
...,...,...,...,...,...,...,...,...,...
2010-11-26 20:58:00,26/11/2010,20:58:00,0.946,0.0,240.43,4.0,0.0,0.0,0.0
2010-11-26 20:59:00,26/11/2010,20:59:00,0.944,0.0,240.0,4.0,0.0,0.0,0.0
2010-11-26 21:00:00,26/11/2010,21:00:00,0.938,0.0,239.82,3.8,0.0,0.0,0.0
2010-11-26 21:01:00,26/11/2010,21:01:00,0.934,0.0,239.7,3.8,0.0,0.0,0.0
2010-11-26 21:02:00,26/11/2010,21:02:00,0.932,0.0,239.55,3.8,0.0,0.0,0.0

In [189]:
serie_electric_power = df_electric_power['Global_active_power']
serie_electric_power

datetime
2006-12-16 17:24:00    4.216
2006-12-16 17:25:00    5.360
2006-12-16 17:26:00    5.374
2006-12-16 17:27:00    5.388
2006-12-16 17:28:00    3.666
                       ...
2010-11-26 20:58:00    0.946
2010-11-26 20:59:00    0.944
2010-11-26 21:00:00    0.938
2010-11-26 21:01:00    0.934
2010-11-26 21:02:00    0.932
Name: Global_active_power, Length: 2075259, dtype: object

In [192]:
serie_electric_power = pd.Series(serie_electric_power)
serie_electric_power

datetime
2006-12-16 17:24:00    4.216
2006-12-16 17:25:00    5.360
2006-12-16 17:26:00    5.374
2006-12-16 17:27:00    5.388
2006-12-16 17:28:00    3.666
                       ...
2010-11-26 20:58:00    0.946
2010-11-26 20:59:00    0.944
2010-11-26 21:00:00    0.938
2010-11-26 21:01:00    0.934
2010-11-26 21:02:00    0.932
Name: Global_active_power, Length: 2075259, dtype: object

In [194]:
serie_property_sales = pd.Series(serie_property_sales['price'])
serie_property_sales

datesold
2007-02-01    407500.0
2007-03-01    328000.0
2007-04-01    465000.0
2007-05-01    339500.0
2007-06-01    451000.0
                ...
2019-03-01    602500.0
2019-04-01    623472.0
2019-05-01    632500.0
2019-06-01    671000.0
2019-07-01    565350.0
Freq: MS, Name: price, Length: 150, dtype: float64